site_name: MP2I au lycée Fénelon Sainte-Marie
# site_url: https://example.com/
repo_url: https://github.com/fortierq/mp2i-2021
nav:
  - OCaml:
    - 1_ocaml/1_variables.ipynb
    - 1_ocaml/2_fonctions.ipynb
    - 1_ocaml/3_conditions.ipynb
    - 1_ocaml/4_recursivite.ipynb
    - 1_ocaml/5_structures_persistantes.ipynb
    - 1_ocaml/6_boucles.ipynb
    - 1_ocaml/7_array_string.ipynb
    - 1_ocaml/8_types_construits.ipynb
plugins:
  - mkdocs-jupyter
theme:
  name: material
  features:
    - navigation.instant
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
