site_name: MP2I au lycée Fénelon Sainte-Marie
site_url: https://mp2i-fsm.github.io/mp2i-2021
repo_url: https://github.com/fortierq/mp2i-2021
nav:
  - Binder: https://mybinder.org/v2/gh/fortierq/mp2i-binder/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Ffortierq%252Fmp2i-2021%26urlpath%3Dlab%252Ftree%252Fmp2i-2021%252F%26branch%3Dmain
  - OCaml:
    - 1_ocaml/1_variables.ipynb
    - 1_ocaml/2_fonctions.ipynb
    - 1_ocaml/3_conditions.ipynb
    - 1_ocaml/4_recursivite.ipynb
    - 1_ocaml/5_structures_persistantes.ipynb
    - 1_ocaml/6_boucles.ipynb
    - 1_ocaml/7_array_string.ipynb
    - 1_ocaml/8_types_construits.ipynb
  - Analyse de programme:
    - Complexité: 2_analyse_programme/1_complexite/complexite.md
    - Preuve de programme: 2_analyse_programme/2_preuve/preuve.md
    - TD preuve de programme: 2_analyse_programme/2_preuve/td_preuve.md
  - Structures séquentielles:
    - Liste, tableau, pile, file: 3_structure_sequentielle/1_pile_file/pile_file.md
    - Dictionnaire et table de hachage: 3_structure_sequentielle/2_hachage_dictionnaire/hachage.md
    - TD 1 (pile et file): 3_structure_sequentielle/td/td_structures1_cor.md
    - TD 2 (listes doublements chaînées): 3_structure_sequentielle/td/td_structures2_cor.md
    - TD 4 (table de hachage): 3_structure_sequentielle/td/cs_hachage/hachage_cs18_cor.md
plugins:
  - mkdocs-jupyter
theme:
  name: material
  custom_dir: overrides
  logo: icon.png
  favicon: icon.png
  features:
    - navigation.instant
    - content.code.annotate
    # - content.tabs.link
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
