site_name: "Cours d'informatique en MP2I au lycée Fénelon Sainte-Marie"
site_url: https://mp2i-fsm.github.io/mp2i-2021
repo_url: https://github.com/fortierq/mp2i-2021
edit_uri: ""
nav:
  - Binder: https://mybinder.org/v2/gh/fortierq/mp2i-binder/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Ffortierq%252Fmp2i-2021%26urlpath%3Dlab%252Ftree%252Fmp2i-2021%252F%26branch%3Dmain
  - Introduction:
    - Cours de prérentrée: 0_intro/stage/stage.md
    - 0_intro/stage/exos_python.ipynb
    - Introduction à la MP2I: 0_intro/0_intro.md
    - Utilisation de Jupyter: 0_intro/1_jupyter.ipynb
    - Rendu des TPs: 0_intro/2_rendu_tp.ipynb
    - Installer Jupyter: 0_intro/install.md
  - OCaml:
    - Cours:
      - 1_ocaml/1_variables.ipynb
      - 1_ocaml/2_fonctions.ipynb
      - 1_ocaml/3_conditions.ipynb
      - 1_ocaml/4_recursivite.ipynb
      - 1_ocaml/5_structures_persistantes.ipynb
      - 1_ocaml/6_boucles.ipynb
      - 1_ocaml/7_array_string.ipynb
      - 1_ocaml/8_types_construits.ipynb
    - Exercices: 
      - 1_ocaml/tp/tp1.ipynb
      - 1_ocaml/tp/tp2.ipynb
      - 1_ocaml/tp/tp3.ipynb
      - 1_ocaml/tp/tp4.ipynb
      - 1_ocaml/tp/tp5.ipynb
      - 1_ocaml/tp/tp6.ipynb
  - Analyse de programme:
    - Complexité: 2_analyse_programme/1_complexite/complexite.md
    - Preuve de programme: 2_analyse_programme/2_preuve/preuve.md
    - TD preuve de programme: 2_analyse_programme/2_preuve/td_preuve.md
  - Structures séquentielles:
    - Liste, tableau, pile, file: 3_structure_sequentielle/1_pile_file/pile_file.md
    - Dictionnaire et table de hachage: 3_structure_sequentielle/2_hachage_dictionnaire/hachage.md
    - "TD 1 : pile et file": 3_structure_sequentielle/td/td_structures1_cor.md
    - "TD 2 : listes doublements chaînées": 3_structure_sequentielle/td/td_structures2_cor.md
    - "TD 3 : cycle dans une liste chaînée": 3_structure_sequentielle/td/td_structures3/td_structures3.md
    - "TD 4 : table de hachage": 3_structure_sequentielle/td/cs_hachage/hachage_cs18_cor.md
  - C: 
    #- Références: 4_c/0_references.md
    - 4_c/cours/0_intro.md
    - 4_c/cours/1_type_base.ipynb
    - Représentation des entiers: 4_c/cours/1_representation/representation_entiers.md
    - Représentation des flottants: 4_c/cours/1_representation/representation_flottants.md
    - 4_c/cours/2_condition_boucle.ipynb
    - 4_c/cours/3_fonction.ipynb
    - 4_c/cours/4_pointeur.ipynb
    - 4_c/cours/5_struct.ipynb
    - 4_c/cours/6_tableau.ipynb
    - 4_c/cours/7_compilation/7_compilation.ipynb
    - 4_c/cours/8_string.ipynb
    - 4_c/cours/9_tableau_2d.ipynb
    - TP:
      - 4_c/tp/1_bitfield.ipynb
      - 4_c/tp/2_liste_chainee.ipynb
      - 4_c/tp/3_representation_binaire.ipynb
      - 4_c/tp/4_dyn_array.ipynb
      - 4_c/tp/5_string.ipynb
      - 4_c/tp/6_bash.ipynb
      - 4_c/tp/7_file/7_file.ipynb
      - 4_c/tp/8_sudoku.ipynb
      - 4_c/tp/9_bash2/9_bash2.ipynb
  - DS:
    - "DS 1 : OCaml, complexité, algorithmique": ds/ds1/ds1.md
    - "DS 2 : Type, pile, file, dictionnaire": ds/ds2/ds2.md
    - "Classement DS 2": ds/ds2/rank_ds2.png
    - "DS 3 : C, représentation des nombres": ds/ds3/ds3.md
plugins:
  - mkdocs-jupyter
theme:
  name: material
  custom_dir: overrides
  logo: icon.png
  favicon: icon.png
  features:
    - navigation.instant
    - content.code.annotate
    # - content.tabs.link
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # - scheme: slate
    #   primary: red
    #   accent: red
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
