name: Jupytext to md
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: pip install jupytext
      - run: |
          find . -name '*.ipynb' | xargs jupytext --to md
      - run: |
          git config --global user.name 'github-actions' 
          git config --global user.email 'github-actions@github.com' 
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          find . -name '*.md' | xargs git add
          git commit -am "Automated autoyapf fixes"
          git push

