name: jupytext
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  jupytext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          pip install git+git://github.com/fortierq/jupytext
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "${changed_file}.";
            jupytext --to ipynb ${changed_file}
          done
